.TH Appender_cpp 3 "22 Dec 2000" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Appender_cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include "log4cpp/Appender.hh"\fR
.br
.SS Namespaces

.in +1c
.ti -1c
.RI "namespace \fBlog4cpp\fR"
.br
.in -1c
.SH AUTHOR
.PP 
Generated automatically by Doxygen for log4cpp from the source code.