.TH HierarchyMaintainer_hh 3 "7 Dec 2000" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HierarchyMaintainer_hh \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fR
.br
\fC#include "log4cpp/Category.hh"\fR
.br
.SS Namespaces

.in +1c
.ti -1c
.RI "namespace \fBlog4cpp\fR"
.br
.in -1c
.SH AUTHOR
.PP 
Generated automatically by Doxygen for log4cpp from the source code.