.TH log4cpp::CategoryStream::Separator 3 "22 Dec 2000" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::CategoryStream::Separator \- Empty struct which acts as a special token to separe log messages in a \fBCategoryStream\fR. 
.SH SYNOPSIS
.br
.PP
\fC#include <Category.hh>\fR
.PP
.SH DETAILED DESCRIPTION
.PP 
Empty struct which acts as a special token to separe log messages in a \fBCategoryStream\fR.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for log4cpp from the source code.