.TH log4cpp::Priority 3 "7 Dec 2000" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::Priority \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Priority.hh>\fR
.PP
.SS Public Types

.in +1c
.ti -1c
.RI "enum \fBPriorityLevel\fR { \fBEMERG\fR = 0, \fBALERT\fR = 100, \fBCRIT\fR = 200, \fBERROR\fR = 300, \fBWARN\fR = 400, \fBNOTICE\fR = 500, \fBINFO\fR = 600, \fBDEBUG\fR = 700, \fBNOTSET\fR = 800 }"
.br
.in -1c
.SS Static Public Methods

.in +1c
.ti -1c
.RI "const string& \fBgetPriorityName\fR (int priority)"
.br
.in -1c
.SH MEMBER ENUMERATION DOCUMENTATION
.PP 
.SS enum log4cpp::Priority::PriorityLevel
.PP
\fBEnumeration values:\fR
.in +1c
.TP
\fB\fIEMERG\fR \fR
.TP
\fB\fIALERT\fR \fR
.TP
\fB\fICRIT\fR \fR
.TP
\fB\fIERROR\fR \fR
.TP
\fB\fIWARN\fR \fR
.TP
\fB\fINOTICE\fR \fR
.TP
\fB\fIINFO\fR \fR
.TP
\fB\fIDEBUG\fR \fR
.TP
\fB\fINOTSET\fR \fR
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS const string& log4cpp::Priority::getPriorityName (int priority)\fC [static]\fR
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for log4cpp from the source code.