.TH log4cpp::NDC::DiagnosticContext 3 "5 Dec 2000" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::NDC::DiagnosticContext \- 
.SH SYNOPSIS
.br
.PP
\fC#include <NDC.hh>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBDiagnosticContext\fR (const string& \fBmessage\fR)"
.br
.ti -1c
.RI "\fBDiagnosticContext\fR (const string& \fBmessage\fR, const DiagnosticContext& parent)"
.br
.in -1c
.SS Public Attributes

.in +1c
.ti -1c
.RI "string \fBmessage\fR"
.br
.ti -1c
.RI "string \fBfullMessage\fR"
.br
.in -1c
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS log4cpp::NDC::DiagnosticContext::DiagnosticContext (const string & message)
.PP
.SS log4cpp::NDC::DiagnosticContext::DiagnosticContext (const string & message, const DiagnosticContext & parent)
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS string log4cpp::NDC::DiagnosticContext::fullMessage
.PP
.SS string log4cpp::NDC::DiagnosticContext::message
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for log4cpp from the source code.