.TH log4cpp::HierarchyMaintainer 3 "7 Dec 2000" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::HierarchyMaintainer \- 
.SH SYNOPSIS
.br
.PP
\fC#include <HierarchyMaintainer.hh>\fR
.PP
.SS Public Types

.in +1c
.ti -1c
.RI "typedef map<const string, \fBCategory\fR*> \fBCategoryMap\fR"
.br
.in -1c
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBHierarchyMaintainer\fR ()"
.br
.ti -1c
.RI "virtual \fB~HierarchyMaintainer\fR ()"
.br
.ti -1c
.RI "virtual \fBCategory\fR& \fBgetInstance\fR (const string& name)"
.br
.ti -1c
.RI "virtual set<\fBCategory\fR*>* \fBgetCurrentCategories\fR () const"
.br
.in -1c
.SS Static Public Methods

.in +1c
.ti -1c
.RI "HierarchyMaintainer& \fBgetDefaultMaintainer\fR ()"
.br
.in -1c
.SS Protected Attributes

.in +1c
.ti -1c
.RI "\fBCategoryMap\fR \fB_categoryMap\fR"
.br
.in -1c
.SH MEMBER TYPEDEF DOCUMENTATION
.PP 
.SS typedef map<const string, \fBCategory\fR*> log4cpp::HierarchyMaintainer::CategoryMap
.PP
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS log4cpp::HierarchyMaintainer::HierarchyMaintainer ()
.PP
.SS virtual log4cpp::HierarchyMaintainer::~HierarchyMaintainer ()\fC [virtual]\fR
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS virtual set<\fBCategory\fR*>* log4cpp::HierarchyMaintainer::getCurrentCategories () const\fC [virtual]\fR
.PP
.SS HierarchyMaintainer& log4cpp::HierarchyMaintainer::getDefaultMaintainer ()\fC [static]\fR
.PP
.SS virtual \fBCategory\fR& log4cpp::HierarchyMaintainer::getInstance (const string & name)\fC [virtual]\fR
.PP
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBCategoryMap\fR log4cpp::HierarchyMaintainer::_categoryMap\fC [protected]\fR
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for log4cpp from the source code.