.TH log4cpp::SimpleLayout 3 "5 Dec 2000" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::SimpleLayout \- 
.SH SYNOPSIS
.br
.PP
\fC#include <SimpleLayout.hh>\fR
.PP
Inherits \fBlog4cpp::Layout\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBSimpleLayout\fR ()"
.br
.ti -1c
.RI "virtual \fB~SimpleLayout\fR ()"
.br
.ti -1c
.RI "virtual char* \fBformat\fR (const \fBLoggingEvent\fR& event)"
.br
.RI "\fIFormats the \fBLoggingEvent\fR data to a string that appenders can log.\fR"
.in -1c
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS log4cpp::SimpleLayout::SimpleLayout ()
.PP
.SS virtual log4cpp::SimpleLayout::~SimpleLayout ()\fC [virtual]\fR
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS virtual char* log4cpp::SimpleLayout::format (const \fBLoggingEvent\fR & event)\fC [virtual]\fR
.PP
Formats the \fBLoggingEvent\fR data to a string that appenders can log.
.PP
Implement this method to create your own layout format. 
.PP
\fBParameters: \fR
.in +1c
.TP
\fB\fIevent\fR\fR The \fBLoggingEvent\fR. 
.PP
\fBReturns: \fR
.in +1c
 an appendable string. 
.PP
Reimplemented from \fBlog4cpp::Layout\fR.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for log4cpp from the source code.