.TH log4cpp 3 "7 Dec 2000" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp \- The top level namespace for all 'Log for C++' types and classes. 
.SH SYNOPSIS
.br
.PP
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBlog4cpp::Appender\fR"
.br
.ti -1c
.RI "class \fBlog4cpp::BasicLayout\fR"
.br
.ti -1c
.RI "class \fBlog4cpp::Category\fR"
.br
.ti -1c
.RI "struct \fBlog4cpp::NDC::DiagnosticContext\fR"
.br
.ti -1c
.RI "class \fBlog4cpp::FileAppender\fR"
.br
.ti -1c
.RI "class \fBlog4cpp::HierarchyMaintainer\fR"
.br
.ti -1c
.RI "class \fBlog4cpp::Layout\fR"
.br
.ti -1c
.RI "struct \fBlog4cpp::LoggingEvent\fR"
.br
.ti -1c
.RI "class \fBlog4cpp::NDC\fR"
.br
.ti -1c
.RI "class \fBlog4cpp::OstreamAppender\fR"
.br
.ti -1c
.RI "class \fBlog4cpp::Priority\fR"
.br
.ti -1c
.RI "class \fBlog4cpp::SimpleLayout\fR"
.br
.ti -1c
.RI "class \fBlog4cpp::SyslogAppender\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
The top level namespace for all 'Log for C++' types and classes.
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for log4cpp from the source code.